################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.c \
D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/psram/stm32_psram_driver.c \
D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_sd.c \
D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_xspi.c \
D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/sdcard/stm32_sdcard_driver.c \
D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_data.c \
D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_driver.c \
D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/user/stm32_user_driver.c 

OBJS += \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.o \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.o 

C_DEPS += \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.d \
./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.o: D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S3xx -DSTM32_EXTMEMLOADER_STM32CUBETARGET -c -I../Core/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.o: D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/psram/stm32_psram_driver.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S3xx -DSTM32_EXTMEMLOADER_STM32CUBETARGET -c -I../Core/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.o: D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_sd.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S3xx -DSTM32_EXTMEMLOADER_STM32CUBETARGET -c -I../Core/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.o: D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/sal/stm32_sal_xspi.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S3xx -DSTM32_EXTMEMLOADER_STM32CUBETARGET -c -I../Core/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.o: D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/sdcard/stm32_sdcard_driver.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S3xx -DSTM32_EXTMEMLOADER_STM32CUBETARGET -c -I../Core/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.o: D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_data.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S3xx -DSTM32_EXTMEMLOADER_STM32CUBETARGET -c -I../Core/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.o: D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp/stm32_sfdp_driver.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S3xx -DSTM32_EXTMEMLOADER_STM32CUBETARGET -c -I../Core/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.o: D:/Workspace/SDQRNG_V8Y/Middlewares/ST/STM32_ExtMem_Manager/user/stm32_user_driver.c Middlewares/ST/STM32_ExtMem_Manager/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32H7S3xx -DSTM32_EXTMEMLOADER_STM32CUBETARGET -c -I../Core/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc -I../../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy -I../../Middlewares/ST/STM32_ExtMem_Loader/core -I../../Middlewares/ST/STM32_ExtMem_Loader/MDK-ARM -I../../Middlewares/ST/STM32_ExtMem_Loader/STM32Cube -I../../Middlewares/ST/STM32_ExtMem_Manager -I../../Middlewares/ST/STM32_ExtMem_Manager/sal -I../../Middlewares/ST/STM32_ExtMem_Manager/nor_sfdp -I../../Middlewares/ST/STM32_ExtMem_Manager/psram -I../../Middlewares/ST/STM32_ExtMem_Manager/sdcard -I../../Middlewares/ST/STM32_ExtMem_Manager/user -I../../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include -I../../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-ST-2f-STM32_ExtMem_Manager

clean-Middlewares-2f-ST-2f-STM32_ExtMem_Manager:
	-$(RM) ./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_extmem.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_psram_driver.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_sd.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sal_xspi.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sdcard_driver.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_data.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_sfdp_driver.su ./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.cyclo ./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.d ./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.o ./Middlewares/ST/STM32_ExtMem_Manager/stm32_user_driver.su

.PHONY: clean-Middlewares-2f-ST-2f-STM32_ExtMem_Manager

